apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-service
  template:
    metadata:
      labels:
        app: wishlist-service
    spec:
      nodeSelector:
        service: "wishlist"
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: wishlist-service
          image: ni04code/aaw-marketplace-wishlist-service:latest
          resources:
            requests:
              cpu: "300m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "600Mi"
          env:
            - name: wishlist_ID
              valueFrom:
                configMapKeyRef:
                  name: wishlist-config
                  key: wishlist_ID
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wishlist-secrets
                  key: JWT_SECRET
            - name: DB_WRITER_HOST
              valueFrom:
                configMapKeyRef:
                  name: wishlist-config
                  key: DB_WRITER_HOST
            - name: DB_READER_HOST
              valueFrom:
                configMapKeyRef:
                  name: wishlist-config
                  key: DB_READER_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: wishlist-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wishlist-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wishlist-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wishlist-config
                  key: DB_NAME
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
spec:
  selector:
    app: wishlist-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30005
  type: NodePort
