apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ni04code/aaw-marketplace-auth-service:latest
          resources:
            requests:
              cpu: "250m"       # 0.25 core reserved
              memory: "256Mi"   # 256 MiB RAM reserved
            limits:
              cpu: "500m"       # max 0.5 core
              memory: "512Mi"   # max 512 MiB RAM 
          env:
            - name: ADMIN_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: ADMIN_TENANT_ID
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: TENANT_ID
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_SECRET
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: ADMIN_JWT_SECRET
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: DB_NAME
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort
