apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_HOST: "order-db"
  DB_PORT: "5432"
  DB_NAME: "aaw-marketplace-order"


---
apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
type: Opaque
data:
  JWT_SECRET: YXV0aF9tc19qd3Rfc2VjcmV0  # Base64-encoded value
  DB_USER: cG9zdGdyZXM=  # Base64 of "postgres"
  DB_PASSWORD: cG9zdGdyZXM= # Base64 of "postgres"
