apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: aaw-marketplace-order-service:latest
          env:
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: TENANT_ID
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: order-secrets
                  key: JWT_SECRET
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: order-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: DB_NAME
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30004
  type: NodePort
