apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_WRITER_HOST: "product-db.cluster-cffqe08z3hsq.us-east-1.rds.amazonaws.com"
  DB_READER_HOST: "product-db.cluster-ro-cffqe08z3hsq.us-east-1.rds.amazonaws.com"
  TENANT_URL: "http://3.90.5.85:30002"
  AUTH_URL: "http://13.216.143.77:30001"
  REDIS_URL: "product-cache-enpt2t.serverless.use1.cache.amazonaws.com"


---
apiVersion: v1
kind: Secret
metadata:
  name: product-secrets
type: Opaque
data:
  JWT_SECRET: YXV0aF9tc19qd3Rfc2VjcmV0  # Base64-encoded value
  DB_USER: cG9zdGdyZXM= # Base64 of "postgres"
  DB_PASSWORD: YWF3Y2Fwc3RvbmUyMDI1
