apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  TENANT_ID: "47dd6b24-0b23-46b0-a662-776158d089ba"
  DB_PORT: "5432"
  DB_NAME: "aaw-marketplace-product"
  DB_WRITER_HOST: "tk-aaw.cluster-crcxfqnmcgs4.us-east-1.rds.amazonaws.com"
  DB_READER_HOST: "tk-aaw.cluster-ro-crcxfqnmcgs4.us-east-1.rds.amazonaws.com"


---
apiVersion: v1
kind: Secret
metadata:
  name: product-secrets
type: Opaque
data:
  JWT_SECRET: YXV0aF9tc19qd3Rfc2VjcmV0  # Base64-encoded value
  DB_USER: cG9zdGdyZXM= # Base64 of "postgres"
  DB_PASSWORD: PH5oOThKVFZbcCpDUGdtQjJob2lzWm4tdy42Rg==
