apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ni04code/aaw-marketplace-product-service:latest
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "384Mi"
          env:
            - name: TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: TENANT_ID
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: product-secrets
                  key: JWT_SECRET
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: product-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: product-config
                  key: DB_NAME
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30003
  type: NodePort
